spring:
  application:
    name: plans

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: OneLeft · plans
